name: Test
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.7
            - name: Install NodeJs
              uses: actions/setup-node@v4.0.2
            - name: Install Dependencies
              run: npm install
            - name: Test
              run: npm test
    Lint:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.7
            - name: Install NodeJs
              uses: actions/setup-node@v4.0.2
            - name: Install Dependencies
              run: npm install 
            - name: Lint
              run: npm run lint
    Build:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.7
            - name: Install NodeJs
              uses: actions/setup-node@v4.0.2
            - name: Install Dependencies
              uses: npm install
            - name: Build
              run: npm run build