name: Test
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.7
            - name: Install NodeJs
              uses: actions/setup-node@v4.0.2
            - name: Install Dependencies
              run: npm install
            - name: npm lint
              run: npm lint
            - name: Test
              run: npm test
            - name: Build Node
              run: npm build