name: Test
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout de Repositorio
              uses: actions/checkout@v4.1.7
            - name: Instalar NodeJS
              uses: actions/setup-node@v4.0.2
            - name: Instalar Dependencias
              run: npm install
            - name: NPM Test
              run: npm test