name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.7
            - name: Setup NodeJS
              uses: actions/setup-node@v4.0.2