name: Output Issues
on:
    issues:
      types: [opened, closed, reopened,]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Context
              run: echo "${{toJson(github.event)}}"