name: Output Issues
on:
    issues:
      types: [opened]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Context
              run: echo "${{toJson(github)}}" 

            - name: Output Issue
              run: echo ${{ steps.issue.output}}